Add support for ssh host

diff --git a/renv b/renv
--- a/renv
+++ b/renv
@@ -2,29 +2,18 @@
 # Remote Environment Management
 
 # Constants
-TAB=$'\t'
-USAGE="Usage: `basename $0` command [--remote git_remote] [--env-file path]"
+declare -r TAB=$'\t'
+declare -r EOL=$'\n'
+declare -r USAGE="Usage: `basename $0` config[:get|:set|:unset] [--host ssh_host|--remote git_remote] [--env-file path]"
 
 # Usage
 [ $# -eq 0 ] && { echo "$USAGE"; exit 1; }
 
-# Require git
-if ! hash git 2>&-; then
-    echo "Git must be installed."
-    exit 1
-fi
-
-# Check if inside a git repository
-git status >&-
-if [ $? == 128 ]; then
-    echo "Not a git repository or git error. Run \"git status\" for more information."
-    exit 1
-fi
-
 # Defaults
-REMOTE=origin
+REMOTE=
 ENV_FILE=""
 PARAMS_COUNT=0
+HOST=
 
 # Arguments
 while [[ $# > 1 ]]; do
@@ -38,6 +27,10 @@ while [[ $# > 1 ]]; do
             ;;
         -e|--env-file)
             ENV_FILE="$1"
+            shift
+            ;;
+        -h|--host)
+            HOST="$1"
             shift
             ;;
         *)
@@ -57,23 +50,55 @@ if [ $PARAMS_COUNT == 0 ]; then
     exit 1
 fi
 
-# Get git remote
-GIT_REMOTE=`git remote -v | grep "$REMOTE" | grep "fetch"`
-if [ -z "$GIT_REMOTE" ]; then
-    echo "\"$REMOTE\" is not a remote in this repository."
+if [ -z "$HOST" ] && [ -n "$REMOTE" ]; then
+    # Require git
+    if ! hash git > /dev/null 2>&1; then
+        echo "Git must be installed to use a Git remote."
+        exit 1
+    fi
+
+    # Check if inside a git repository
+    git status > /dev/null 2>&1
+    if [ $? == 128 ]; then
+        echo "Not a git repository, or other git error. Run \"git status\" for more information."
+        exit 1
+    fi
+
+    # Get git remote
+    GIT_REMOTE=`git remote -v | grep "$REMOTE" | grep "fetch"`
+    if [[ $GIT_REMOTE = *$EOL* ]]; then
+        echo "Ambigous remote \"$REMOTE\"."
+        exit 1
+    fi
+
+    if [ -z "$GIT_REMOTE" ]; then
+        echo "\"$REMOTE\" is not a remote in this repository."
+        exit 1
+    fi
+
+    HOST=`expr "$GIT_REMOTE" : "^.*${TAB}\(.*\):.* "`
+    REMOTE_DIR=`expr "$GIT_REMOTE" : "^.*${TAB}.*@.*:\(.*\) "`
+
+    # If ENV_FILE isn't set, try remote .env file
+    if [ -z "$ENV_FILE" ]; then
+        ENV_FILE="${REMOTE_DIR}/.env"
+    fi
+fi
+
+# Last check
+if [ -z "$HOST" ]; then
+    echo "No host or remote specified."
+    exit 1
+fi
+if [ -z "$ENV_FILE" ]; then
+    echo "No remote .env file specified."
     exit 1
 fi
 
-REMOTE_HOST=`expr "$GIT_REMOTE" : "^.*${TAB}\(.*\):.* "`
-REMOTE_DIR=`expr "$GIT_REMOTE" : "^.*${TAB}.*@.*:\(.*\) "`
-
-# If ENV_FILE isn't set, try remote .env file
-if [ -z "$ENV_FILE" ]; then
-    ENV_FILE="${REMOTE_DIR}/.env"
-fi
+APP=`expr "$HOST" : '.*@\([^:/]*\)'`
 
 # Check if file exists on remote
-if ! ssh $REMOTE_HOST stat $ENV_FILE \> /dev/null 2\>\&1; then
+if ! ssh $HOST stat $ENV_FILE \> /dev/null 2\>\&1; then
     echo "\"$ENV_FILE\" doesn't exist on the remote. Try specifying the path with the --env-file argument."
     exit 1
 fi
@@ -86,7 +111,7 @@ case $PARAMS[0] in
         fi
 
         KEY="${PARAMS[1]}"
-        ENV=`ssh $REMOTE_HOST cat "$ENV_FILE" | grep "^\<export\> ${KEY}="`
+        ENV=`ssh $HOST cat "$ENV_FILE" | grep "^\<export\> ${KEY}="`
         VAL=`expr "$ENV" : "^\<export\> [^=]*=\(.*\)"`
 
         echo "$VAL"
@@ -100,7 +125,7 @@ case $PARAMS[0] in
         KEY=`expr "${PARAMS[1]}" : "\([^=]*\)=.*"`
         NEW_VAL=`expr "${PARAMS[1]}" : "[^=]*=\(.*\)"`
 
-        ENV=`ssh $REMOTE_HOST cat "$ENV_FILE" | grep "^\<export\> ${KEY}="`
+        ENV=`ssh $HOST cat "$ENV_FILE" | grep "^\<export\> ${KEY}="`
         VAL=`expr "$ENV" : "^\<export\> [^=]*=\(.*\)"`
 
         if [ "$VAL" == "$NEW_VAL" ]; then
@@ -109,9 +134,9 @@ case $PARAMS[0] in
         fi
 
         if [ -n "$ENV" ]; then
-            ssh $REMOTE_HOST "sed -i \"s|export ${KEY}=${VAL}|export ${KEY}=${NEW_VAL}|\" \"$ENV_FILE\""
+            ssh $HOST "sed -i \"s|export ${KEY}=${VAL}|export ${KEY}=${NEW_VAL}|\" \"$ENV_FILE\""
         else
-            echo "export ${KEY}=${NEW_VAL}" | ssh $REMOTE_HOST "cat >> $ENV_FILE"
+            echo "export ${KEY}=${NEW_VAL}" | ssh $HOST "cat >> $ENV_FILE"
         fi
 
         echo "${KEY}=${NEW_VAL}"
@@ -131,16 +156,16 @@ case $PARAMS[0] in
             exit 0
         fi
 
-        ENV=`ssh $REMOTE_HOST cat "$ENV_FILE" | grep "^\<export\> ${KEY}="`
+        ENV=`ssh $HOST cat "$ENV_FILE" | grep "^\<export\> ${KEY}="`
 
         if [ -z "$ENV" ]; then
             exit 0
         fi
 
-        ssh $REMOTE_HOST "sed -i \"/$KEY/d\" $ENV_FILE"
+        ssh $HOST "sed -i \"/$KEY/d\" $ENV_FILE"
         ;;
     config*)
-        ENV=`ssh $REMOTE_HOST cat "$ENV_FILE"`
+        ENV=`ssh $HOST cat "$ENV_FILE"`
         KEYS=()
         VALS=()
         MAX_LEN=0
@@ -158,7 +183,7 @@ case $PARAMS[0] in
             fi
         done <<< "$ENV"
 
-        echo "=== $REMOTE Config Vars"
+        echo "=== $APP Config Vars"
         for i in "${!KEYS[@]}"; do
             KEY=${KEYS[${i}]}
             LEN=${#KEY}
